Server Side Events  + Edit / delete activities tests study groups + limesurvey owners + statements LRS endpoint
e-ucm/simva pull request #134
Opened 2024-10-24 15:08 UTC by jujusb

2025-02-24 18:07 UTC, imartinezortiz requested changes

2025-02-24 18:07 UTC, imartinezortiz commented on .github/workflows/docker-publish.yml
If DCOS is approve, we do not need it. Remove it to avoid GH Actions clutter

2025-02-24 18:07 UTC, imartinezortiz commented on Dockerfile
> +FROM node:20.18.3-bullseye
Update to 22 LTS

2025-02-25 14:39 UTC, jujusb commented on .github/workflows/docker-publish.yml
removed

2025-02-25 14:39 UTC, jujusb commented on Dockerfile
> +FROM node:20.18.3-bullseye
updated

2025-02-26 13:20 UTC, imartinezortiz approved these changes

2025-03-03 11:13 UTC, imartinezortiz approved these changes

2025-03-03 16:42 UTC, merged